image: build_img 

build:
  stage: build
  script:
    - alias semver="git describe --long | sed -e 's/\(.*\)\-\(.*\)\-\(.*\)/\1\-\2+\3/g'"
    - echo "config..."
    - echo "linting..."
    - echo "cppcheck..."
    - echo "building..."

deploy:
    stage: deploy
    script: conan upload -r artifactory proj1/`semver`@gitlab/develop
