image: gcc

build:
  stage: build
  script:
    - echo "config..."
    - echo "linting..."
    - echo "cppcheck..."
    - echo "building..."

deploy:
    stage: deploy
    script: conan upload -r artifactory proj1/`semver`@gitlab/develop